# -*- coding: utf-8 -*-
"""6_move_zeroes[283].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QreuzsLGKEvs6h633fddPouCERM3sHY_
"""

# Move Zeroes Function
def moveZeroes(nums):
    """
    Moves all 0's to the end of the list while maintaining the order of non-zero elements.
    Modifies the list in-place.
    """
    i = 0  # Position to place the next non-zero element
    for j in range(len(nums)):
        if nums[j] != 0:
            nums[i], nums[j] = nums[j], nums[i]
            i += 1

# Test the function
nums = [0, 1, 0, 3, 12]
print("Original list:", nums)

moveZeroes(nums)

print("After moving zeroes:", nums)

