# -*- coding: utf-8 -*-
"""is_Subsequence_392.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rcoh2lfypd1JEQzZuolFswGvfLfV9H4Y
"""

# LeetCode-style class
class Solution:
    def isSubsequence(self, s: str, t: str) -> bool:
        i, j = 0 , 0
        while i < len(s) and j < len(t):
            if s[i] == t[j]:
                i += 1
            j += 1
        return i == len(s)  # Same as: return True if i == len(s) else False

# Create an instance of the Solution class
sol = Solution()

# Test the function with input
s = "abc"
t = "ahbgdc"

# Call the method and print the result
result = sol.isSubsequence(s, t)
print(f"Is '{s}' a subsequence of '{t}'? → {result}")